tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT

tasks:
  - init: pip install boto3 # Or pip3 install boto3 if you want to be explicit about Python 3
          pip install matplotlib
    command: python import_lib.py # Or any other command to run your project